### ISSUE TITLE
moonraker update manager

### ISSUE THREAD

**Issue by StofflHD** [ballaswag/guppyscreen#12]
Hi ballaswag,

is it possible to use the moonraker update manager to update guppyscreen?

Thanks,
StofflHD

**Comment by ballaswag** [comment]
Will take a look at the update flow.

**Comment by ballaswag** [comment]
Moonraker update might not be possible from my reading of its code. Its service restart is systemd base and K1 doesn't have that. It's deprecated install_script option is only for reading package list for apt, so no custom installer scripts. For now I might just add an update button in guppy screen to check and update.

**Comment by StofflHD** [comment]
Thanks for taking a look at it.
