### ISSUE TITLE
Warning: belts doesn't seem to have the correct name A and B (extracted from the filename.csv) // Belts estimated similarity: 90.0%

### ISSUE THREAD

**Issue by Glod76** [ballaswag/guppyscreen#14]
Warning: belts doesn't seem to have the correct name A and B (extracted from the filename.csv)
// Belts estimated similarity: 90.0%

**Comment by ballaswag** [comment]
This is not an issue. The original klippain scripts renames the raw files with a and b suffix. So it expects the file names to have an and b, but it’s not a requirement.
