### ISSUE TITLE
IDEA

### ISSUE THREAD

**Issue by Zipciok** [ballaswag/guppyscreen#2]
Hi, i have idea. It would be nice to have one tab for macros that user can edit  for example like that 
![image](https://github.com/ballaswag/guppyscreen/assets/78239674/54769535-0bd8-4347-9001-e3265c89047c)

**Comment by Zipciok** [comment]
Thanks for fast response. I have question, thats my belt graph. what is ideal one? how much HZ should be? 110hz?
![403946132_1031292878124866_5047862516187416063_n](https://github.com/ballaswag/guppyscreen/assets/78239674/eb901463-e5f5-47d4-9bed-69bacd5a2faa)

I just click start on this screen.
![belts_calibration](https://github.com/ballaswag/guppyscreen/assets/78239674/0a5003d5-bf72-4239-9918-87e0b039f3dd)

**Comment by ballaswag** [comment]
See here https://github.com/Frix-x/klippain-shaketune/blob/main/docs/macros/belts_tuning.md I'm no expert at printer tuning.

**Comment by Zipciok** [comment]
And one more thing. I would love to have file sorting system, for example by date of addition.

**Comment by Zipciok** [comment]
Wow so fast replay. Thanks, that help alot

**Comment by ballaswag** [comment]
[Screencast from 12-20-2023 12:07:25 PM.webm](https://github.com/ballaswag/guppyscreen/assets/145094472/2eea92e1-4a93-41a4-a161-8c56e3ac3fc6)
Expanded macros with parameters.

**Comment by Zipciok** [comment]
> Screencast.from.12-20-2023.12.07.25.PM.mp4 
> Expanded macros with parameters.

That's cool, this is what i needed. There will be option to Pin 📌 few and have them displayed on the top of this list?

**Comment by ballaswag** [comment]
yeah some kind of filtering and option to pin and unpin will be part of it.

**Comment by Zipciok** [comment]
> yeah some kind of filtering and option to pin and unpin will be part of it.

Thanks, you are making realy good job!
