### ISSUE TITLE
New wireless auto connection not working

### ISSUE THREAD

**Issue by javirub** [ballaswag/guppyscreen#24]
When i connected with the oem screen interface to a wireless connection, it gets saved and autoconnect to that network everytime you power on-off creality k1 printer.

With guppy screen, the previous saved network still reconnecting, but when you add a new one, you have to connect manually everytime you restart the machine.

**Comment by ballaswag** [comment]
Thanks for the report. Issue most likely due to guppy not issuing a save_config against wpa supplicant after switching networks. Will take a look at fixing for next release.

**Comment by javirub** [comment]
> Thanks for the report. Issue most likely due to guppy not issuing a save_config against wpa supplicant after switching networks. Will take a look at fixing for next release.

Yes, anyway for some reason, the /etc/wpa_supplicant.conf (it should be in /etc/wpa_supplicant/wpa_supplicant.conf) has no stored data inside, put manually my wireless data and still not working. Finally i made it work with wpa_cli
