### ISSUE TITLE
Feature request: Change temperatures while printing

### ISSUE THREAD

**Issue by function3d** [ballaswag/guppyscreen#26]
I miss the possibility to change the temperatures (hotend and bed) while printing that was in the creality ui.

Thanks

**Comment by ballaswag** [comment]
If you go to the main panel with the graph, then click on the extruder/bed temperature, a numpad will popup. Does change it this way work during prints?

**Comment by function3d** [comment]
The screen while printing is not the same as the main screen when idle, no
temperature field or popup during printing

**Comment by function3d** [comment]
Ok, now I have seen that you can go back to the print window and then further back to the main window
