### ISSUE TITLE
Pause, cancel and fine tune button vanished on small screen

### ISSUE THREAD

**Issue by neturmel** [ballaswag/guppyscreen#27]
in 0.0.19-beta, on smallscreen (KE nebula pad), when printing, there is a progress bar but no pause fine tune and cancel button anymore. They may be hidden.

**Comment by ballaswag** [comment]
oh no, let me fix. I must have verified in the small resolution. Changed something for larger screen and forgot to double check m.

**Comment by ballaswag** [comment]
I see the buttons on my simulator for smaller screens. Can you share a picture of what you're seeing.
![ss-print](https://github.com/ballaswag/guppyscreen/assets/145094472/42349f6b-a706-4b7f-88b0-73ba02a780b6)

**Comment by neturmel** [comment]
![image](https://github.com/ballaswag/guppyscreen/assets/74895293/e390191f-18ef-498a-808a-161149dafa82)

I updated from 0.0.18 (if that matters)

**Comment by ballaswag** [comment]
I can’t reproduce on the simulator and I don’t have the actual hardware. I tried to redo the alignment in 0.0.20-beta latest version. Please let know if that resolves the issue if you get a chance to update.

**Comment by neturmel** [comment]
I solved it! Updated to 0.0.20-beta to no avail. But than I realized, that the buttons were indeed there, until the peview image was rendered. Them I realized, I sliced with Orca and a preview image size of 32x32, 300x300 (because this worked better in creality screen), may be this was the problem? Tried now with 96x96, 300x300 and all is well.
