### ISSUE TITLE
Screen freeze on K1 mid print

### ISSUE THREAD

**Issue by tarodofchaos** [ballaswag/guppyscreen#29]
The screen freezes in the middle of a print and it won't respond to touch unless you restart the service or manually power cycle the printer.

This happens with a V2 Creality K1

- Firmware version 1.3.3.3
- KAMP-for-K1-Series v1.1.2-8-g9e942708
- mainsail v2.9.1
- moonraker v0.8.0-262

Attached guppy log.
[guppyLog.txt](https://github.com/ballaswag/guppyscreen/files/13986531/guppyLog.txt)

**Comment by mattskent** [comment]
Having the same issue here

**Comment by ballaswag** [comment]
Thanks for the report. Going to try two things. In the short term if I can track down where the crash happens, I’ll provide some auto restart so guppy screen will just automatically start up again. In the long term, will track down the crash and fix the issue.

**Comment by ballaswag** [comment]
Latest 0.0.20-beta automatically restarts guppy screen if it dies. If you get a chance to update, please let me know if it works better.

**Comment by mattskent** [comment]
Just confirming I haven't had any screen freezes so far on the latest version

**Comment by ballaswag** [comment]
Closing this since the latest version will auto respawn if guppy screen is terminated.
