### ISSUE TITLE
No Thumbnail of the Print

### ISSUE THREAD

**Issue by JayNRW** [ballaswag/guppyscreen#3]
First, a great job and i will subscribe you :)

I am Using creality print and i dont see thumbnails in guppyscreen, can you help  me workauround this :)?

**Comment by ballaswag** [comment]
Missing thumbnails for creality print is most likely due to the official moonraker missing the metadata parser for the creality slicer. I added it in this branch https://github.com/ballaswag/moonraker/tree/creality-print-slicer.
