### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by Fcop** [ballaswag/guppyscreen#35]
I have this issue

root@K1Max-51AE /root [#] sh -c "$(wget --no-check-certificate -qO - https://raw.githubusercontent.com/ballaswag/guppyscreen/main/installer.sh)"
Found screen virtual size 480, 1600
=== Installing Guppy Screen ===
Checking for a working Moonraker
 Found klipper path: /usr/share/klipper
 Found config dir: /usr/data/printer_data/config
 Downloading asset: guppyscreen.tar.gz
tar: short read
Did not find guppyscreen in /usr/data/guppyscreen. GuppyScreen must be extracted in /usr/data/guppyscreen

**Comment by ballaswag** [comment]
Run `date` on via ssh. If the time shown is out of sync, then you need to for sync it so that SSL will work. You can try force syncing it by running `/etc/init.d/S49ntp restart`. Once the time is fixed, you can try running Guppy's installer again.
