### ISSUE TITLE
Unable to select/see spoolman

### ISSUE THREAD

**Issue by ItsDeidara** [ballaswag/guppyscreen#36]
I'm sure it's user error but as of right now I am unable to use spoolman after installing Guppyscreen.

It is currently grayed out and not able to be tapped on the touch screen itself, and "invisible" within Fluidd. I am able to see the option of Spoolman within my layout editor, but even enabled it does not seem to appear.

Is there a setting I missed that I was supposed to setup?

**Comment by ballaswag** [comment]
Did you enable spoolman in moonraker? See https://moonraker.readthedocs.io/en/latest/configuration/#spoolman

**Comment by ItsDeidara** [comment]
I did not enable it moonraker, good catch! I just did, and did a full reboot afterwards. Unfortunately it did not make a difference. It is not showing up in Fluidd and the direct URL within moonraker does not seem to work
