### ISSUE TITLE
After update to moonraker v0.8.0-309-gf946e6a2 guppyscreen "freezes" on initialise printer

### ISSUE THREAD

**Issue by P-C-R** [ballaswag/guppyscreen#38]
freezes on initlalise printer. acces to mainsail is okay.

**Comment by P-C-R** [comment]
Spoolman was the culprit. Sometimes moonraker will not connect with spoolman...

**Comment by KennyVB** [comment]
> Spoolman was the culprit. Sometimes moonraker will not connect with spoolman...

how did you solve it ?
