### ISSUE TITLE
newest mainsail update breaks guppy

### ISSUE THREAD

**Issue by P-C-R** [ballaswag/guppyscreen#42]
cpuld it be that 

https://github.com/mainsail-crew/mainsail/pull/1749

breaks guppy?

**Comment by ballaswag** [comment]
Guppy screen integrates spoolman through moonraker and not mainsail. I'm aware there's a change in spoolman and I haven't verify that change. If you haven't updated spoolman or moonraker, guppy should continue to work.

If the upstreams break backward compatibility then I'll look to add support on future releases.

**Comment by ballaswag** [comment]
If related to spoolman, newest release handles some of the case that crashed Guppy Screen. Closing for now, please reopen if you still see the issue.
