### ISSUE TITLE
Change display orientation to portrait on Creality ender3 ke

### ISSUE THREAD

**Issue by kevdliu** [ballaswag/guppyscreen#46]
Hello,

Is it possible to change the display orientation of guppyscreen? I have a Creality ender3 ke, which has a vertical display, and the UI is displaying sideways in landscape. 

Thank you

**Comment by ballaswag** [comment]
It won't look good in portrait because the UI elements will be squished. You can try printing one of the landscape mounts for the KE from printables.

**Comment by kevdliu** [comment]
Good to know! I'll try printing the mount. Thank you
