### ISSUE TITLE
Cooldown button below Load/Unload

### ISSUE THREAD

**Issue by halTWO3** [ballaswag/guppyscreen#60]
Assuming Cooldown Button below Load and Unload is suppose to turn on the fans? After unloading and loading, I press the cooldown button and nothing. Fans are still off.

**Comment by ballaswag** [comment]
Cooldown is mapped to a macro in guppyscreen.json. You can change that to do anything in terms of cooldown procedures for a specific printer.

**Comment by halTWO3** [comment]
Will check it out, tyvm.
