### ISSUE TITLE
Load filament button ignores selected temperature 

### ISSUE THREAD

**Issue by dprossner** [ballaswag/guppyscreen#68]
Regardless of what temperature I set for loading and unloading filament, the printer heats up to 240 degrees which is the maximum option

**Comment by TheWebMachine** [comment]
I can confirm this behavior. Always 240 on Load/Unload, regardless of temp selection.

**Comment by ballaswag** [comment]
nightly build and next stable release will have fix. Load/unload will respect the selected temp and extrude length.
