### ISSUE TITLE
Ender 3 V3 KE  -- Display Sleep Problem

### ISSUE THREAD

**Issue by Liionboy** [ballaswag/guppyscreen#74]
Hello,

There are a problem with selecting Display Sleep on Nebula Pad , you can select only 5 hours , can't select Never or something else, i try all posibility.

Thanks

**Comment by ballaswag** [comment]
The nightly build should fix this, will be in next stable release as well. For now you can edit guppyconfig.json `display_sleep_sec` to -1 for Never.

**Comment by davphoenix31** [comment]
Yes, I do confirm the same for me on KE. Additionally, it seems the default value is low, something like 30s whereas the first value on the drop-down is 10min

**Comment by ballaswag** [comment]
Just released 0.0.23-beta, please update and see if issue is resolved.

**Comment by davphoenix31** [comment]
Yes, I do confirm, working well with 0.0.23-beta, well done.
