### ISSUE TITLE
stuck with non existing jon in Queue

### ISSUE THREAD

**Issue by avilshadow** [ballaswag/guppyscreen#85]
guppu screen 0.0.24-beta
printerv3KE

Used 0.0.21beta before, updated with the button on the screen, not when trying to start new print got this screen on the screenshot.
QUwuw/ View job buttons are also non-functional.
Could start prijnt with web UI..

![image](https://github.com/ballaswag/guppyscreen/assets/7083556/4a3f7131-337e-4073-b6b7-8d9423af600b)

**Comment by Strahler85** [comment]
I have the same issue with beta 0.24. I can start prints over fluiid and OrcaSlicer.

**Comment by natesaninja** [comment]
Same issue as well

**Comment by Teense** [comment]
Same issue, KE version 24.

**Comment by ballaswag** [comment]
Found the issue. Will make a release soon.

**Comment by ballaswag** [comment]
0.0.25-beta is out, fixes all the things and has  better speed/flow/layer count logic too.
