### ISSUE TITLE
Revert to a previous verions

### ISSUE THREAD

**Issue by Liionboy** [ballaswag/guppyscreen#86]
Hello,

How can i revert back to version 23 because 24 is full of bug at display:

![image](https://github.com/ballaswag/guppyscreen/assets/87735636/b81eedb5-3535-493f-b78d-b0fe1c2ba80d)

Thanks

**Comment by Liionboy** [comment]
No speed, no thumbnail, no correct Layers, Time Rmaining not work

**Comment by ballaswag** [comment]
Rerun the installer, I pulled 0.0.24-beta. Latest should be reverted to 0.0.23-beta now.

**Comment by Liionboy** [comment]
I did and still is 0.0.24

Thanks

**Comment by Liionboy** [comment]
Oh with update don't work, i run installer and worked.

Thanks

**Comment by martinrevert** [comment]
Sorry for the offtopic @Liionboy , How did you phisically achieve to rotate the Nebula pad? Did you printed a custom support to get the screen horizontal? If so, do you have the STL?. Thanks!

**Comment by Liionboy** [comment]
Hello,

You find here

https://www.printables.com/model/706657-creality-ender-3-v3-e3v3-se-ke-and-cr-10-se-portra

**Comment by ballaswag** [comment]
0.0.25-beta is out, fixes all the things and has  better speed/flow/layer count logic too.
