### ISSUE TITLE
Ender 3 V3 KE touches no longer working

### ISSUE THREAD

**Issue by grantland** [ballaswag/guppyscreen#88]
I updated to latest today which I assume is 0.0.25-beta and touches are no longer working on the Nebula Pad. Not sure if this is related to this: https://github.com/ballaswag/guppyscreen/issues/54#issuecomment-2080342699

**Comment by ballaswag** [comment]
Well that was dumb of me. Fixed the calibration flow and pushed 0.0.26-beta. If not please reopen.

**Comment by grantland** [comment]
It works, thanks!
