### ISSUE TITLE
keypad presses produce multiple inputs

### ISSUE THREAD

**Issue by gbrowerjr** [ballaswag/guppyscreen#92]
I have a creality K1c running latest klipper, fluidd, moonraker and guppyscreen. All installed from guilouz's helper script. Updates handled from Fluidd interface.

When attempting to input numbers like to change hotend temperature for instance and press the #2 button from the keypad anywhere from 2-5 #2s will show in the input box. tapping the backspace button will remove a random number of characters from the input box. Appropriate actions from all other icons are performed correctly. It is just the popup keypad. The correct numbers show up in the input box just multiple of them. Like i tapped the button repeatedly.

**Comment by ballaswag** [comment]
Update to latest version should fix this.
