### ISSUE TITLE
Ender 3 V3 KE - vibration compensation

### ISSUE THREAD

**Issue by Teense** [ballaswag/guppyscreen#93]
Firstly, thank you for GuppyScreen, incredible GUI!
I'd like to know how to use Input shaper and belts/shake with ADXL345 on KE.

In factory GUI, you just run compensating process and in the half you move vibration sensor from hotend to bed.
In Guppy i'm little lost. I must firstly run x axis, than y axis and than click save (or is it saved automaticaly)? And for what are frequency sliders and selection with default mzv. Same belts/shake.

I'd appreciate it if you could clear that up for me. Or if it's possible to make it simple like in original GUI.
Thank you, Teense.

**Comment by ballaswag** [comment]
The input shaping (calibration) for default is wrong at least on the K1. It always select one shaper type regardless of other method fit better.

For the KE, you can run shaping then save in guppy screen. The belt shake stuff is for corexy mainly and not applicable to KE (that's my understanding at least).

The frequency slider in the belt/shake panel is the for tuning. For example, after input shaping, the graph shows you have bad vibrations at a specific frequency. Then you can set slider to said frequency, run it to find where the rattle comes from. Fix it, then run again until you're happy with your tune.

**Comment by Teense** [comment]
Thanks :)
